version: '3.7'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-reactive-processor
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=my.topic:1:1
    depends_on:
      - zookeeper
    networks:
      - reactive-process-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --zookeeper zookeeper:2181 --list 2>&1 | grep \"my.topic\""]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - reactive-process-network
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_LISTEN_ADDRESS=cassandra
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
    networks:
      - reactive-process-network
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50

  reactive-process:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - cassandra
      - kafka
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_HOST=cassandra
      - KAFKA_HOST=kafka
    networks:
      - reactive-process-network

networks:
  reactive-process-network:
