Spring Cloud Stream Reactive Processor Basic Sample
==================================================

This is a Spring Cloud Stream reactive processor sample.

## Requirements

To run this sample, you will need to have installed:

* Java 8 or Above

## Running the application

The following instructions assume that you have docker installed on your system.

* Go to the application root
* `docker-compose up -d` (Starts Kafka, Zookeeper and Scylla within their own container)

* `./mvnw clean package` (builds the application from source)

* `docker exec -i scylla cqlsh -e "CREATE KEYSPACE IF NOT EXISTS pricing WITH REPLICATION = { 'class':'SimpleStrategy', 'replication_factor':1 };"`
(Will create the keyspace needed for the sample application

* `java -jar target/reactive-processor-0.0.1-SNAPSHOT.jar`

The main application contains the reactive processor that receives textual data for a duration and aggregates them.
It then sends the aggregated data through the outbound destination of the processor.

The application also provides a source and sink for testing.
Test source will generate some text every second and the test sink will verify that the processor has accumulated the text over a duration.
Test source is bound to the same broker destination where the processor is listening from.
Similarly test sink is bound to the same broker destination where the processor is producing to.

You will see output similar to the following on the console every 5 seconds.

```
Data received: foobarfoobarfoo
Data received: barfoobarfoobar
Data received: foobarfoobarfoo
Data received: foobarfoobarfoo
```

* `docker-compose down`

### Running the application with Cassandra instead of Scylla

If you wish to use Cassandra instead of Scylla, simply comment out the scylla section of the docker-compose.yml and
uncomment the cassandra section. Then follow the instructions above in "Running the application"