spring:
  data:
    cassandra:
      keyspaceName: pricing
      port: 9042
      schemaAction: recreate
      username: cassandra
      password: cassandra
      contact-points: ${CASSANDRA_HOST}
  cloud:
    stream:
      bindings:
        output:
          destination: transformed
        test-sink:
          destination: transformed
        input:
          destination: testtock
        test-source:
          destination: testtock
      kafka:
        binder:
          brokers: ${KAFKA_HOST}
